
  CREATE OR REPLACE PACKAGE "ODMRSYS"."ODMR_PROJECT_SEC" 
AUTHID DEFINER AS

  FUNCTION project_exist(p_user IN VARCHAR2, p_project_name VARCHAR2) RETURN BOOLEAN;

  FUNCTION project_exist(p_project_ids ODMR_OBJECT_IDS) RETURN BOOLEAN;

  PROCEDURE set_timestamp(p_project_id IN NUMBER, p_last_updated_time IN TIMESTAMP);

  FUNCTION PROJECT_CREATE(p_user IN VARCHAR2, p_project_name IN VARCHAR2, p_comment IN VARCHAR2) RETURN NUMBER;

  PROCEDURE PROJECT_DELETE(p_project_ids IN ODMR_OBJECT_IDS, p_db_objects IN OUT NOCOPY ODMR_INTERNAL_UTIL.DB_OBJECTS);

  PROCEDURE PROJECT_RENAME(p_project_id IN NUMBER, p_project_name IN VARCHAR2);

  PROCEDURE SET_COMMENT(p_project_id IN NUMBER, p_comment IN VARCHAR2);

END ODMR_PROJECT_SEC;
/
 
