<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2011 rel. 3 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:n1="osdm_g" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="altova altovaext clitype fn iso4217 ix java link n1 sps xbrldi xbrli xlink xs xsd xsi">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<html>
			<head>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2011 rel. 3 sp1 (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=7"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:2cm; margin-right:2cm; margin-top:2cm; margin-bottom:2cm } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body style="empty-cells:show; font-family:Tahoma; font-size:xx-small; text-align:left; vertical-align:top; word-wrap:break-word; ">
				<center>
					<span style="font-size:medium; font-weight:bold; ">
						<xsl:text>Glossary Details</xsl:text>
					</span>
				</center>
				<br/>
				<xsl:for-each select="$XML">
					<xsl:for-each select="n1:root">
						<br/>
						<table style="width:15cm; " border="0" cellpadding="3" cellspacing="0">
							<xsl:variable name="altova:CurrContextGrid_0A618C00" select="."/>
							<tbody>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; width:4cm; ">
										<span style="font-weight:bold; ">
											<xsl:text>Glossary Name</xsl:text>
										</span>
									</td>
									<td style="background-color:#a5e7ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; width:11cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<h1>
													<xsl:for-each select="n1:GlossaryName">
														<span style="font-size:xx-small; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</h1>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:GlossaryName) &gt; 0">
														<h1>
															<xsl:for-each select="n1:GlossaryName">
																<span style="font-size:xx-small; ">
																	<xsl:apply-templates/>
																</span>
															</xsl:for-each>
														</h1>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<h1>
													<xsl:for-each select="n1:GlossaryName">
														<span style="font-size:xx-small; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</h1>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<h1>
													<xsl:for-each select="n1:GlossaryName">
														<span style="font-size:xx-small; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</h1>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<h1>
													<xsl:for-each select="n1:GlossaryName">
														<span style="font-size:xx-small; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</h1>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:4cm; ">
										<span style="font-weight:bold; ">
											<xsl:text>Description</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:Description">
													<xsl:for-each select="n1:DescriptionDetails">
														<xsl:for-each select="n1:DescriptionRow">
															<xsl:apply-templates/>
															<br/>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="count(n1:Description/n1:DescriptionDetails/n1:DescriptionRow) &gt; 0">
														<xsl:for-each select="n1:Description">
															<xsl:for-each select="n1:DescriptionDetails">
																<xsl:for-each select="n1:DescriptionRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:choose>
													<xsl:when test="count(n1:Description/n1:DescriptionDetails/n1:DescriptionRow) &gt; 0">
														<xsl:for-each select="n1:Description">
															<xsl:for-each select="n1:DescriptionDetails">
																<xsl:for-each select="n1:DescriptionRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise/>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:Description">
													<xsl:for-each select="n1:DescriptionDetails">
														<xsl:for-each select="n1:DescriptionRow">
															<xsl:apply-templates/>
															<br/>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:Description">
													<xsl:for-each select="n1:DescriptionDetails">
														<xsl:for-each select="n1:DescriptionRow">
															<xsl:apply-templates/>
															<br/>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:4cm; ">
										<span style="font-weight:bold; ">
											<xsl:text>File Name</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:FileName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:FileName) &gt; 0">
														<xsl:for-each select="n1:FileName">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:FileName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:FileName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:FileName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:4cm; ">
										<span style="font-weight:bold; ">
											<xsl:text>Incomplete Modifiers</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:IncompleteModifiers">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:IncompleteModifiers) &gt; 0">
														<xsl:for-each select="n1:IncompleteModifiers">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:IncompleteModifiers">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:IncompleteModifiers">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:IncompleteModifiers">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:4cm; ">
										<span style="font-weight:bold; ">
											<xsl:text>Case Sensitive</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:CaseSensitive">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:CaseSensitive) &gt; 0">
														<xsl:for-each select="n1:CaseSensitive">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:CaseSensitive">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:CaseSensitive">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:CaseSensitive">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:4cm; ">
										<span style="font-weight:bold; ">
											<xsl:text>Unique Abbreviations</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:UniqueAbbreviations">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:UniqueAbbreviations) &gt; 0">
														<xsl:for-each select="n1:UniqueAbbreviations">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:UniqueAbbreviations">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:UniqueAbbreviations">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:UniqueAbbreviations">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:4cm; ">
										<span style="font-weight:bold; ">
											<xsl:text>Separator Type</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:SeparatorType">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:SeparatorType) &gt; 0">
														<xsl:for-each select="n1:SeparatorType">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:SeparatorType">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:SeparatorType">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:SeparatorType">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td style="background-color:#d9f5ff; border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:4cm; ">
										<span style="font-weight:bold; ">
											<xsl:text>Separator Char</xsl:text>
										</span>
									</td>
									<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:11cm; ">
										<xsl:choose>
											<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
												<xsl:for-each select="n1:SeparatorChar">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
												<xsl:choose>
													<xsl:when test="string-length(n1:SeparatorChar) &gt; 0 or n1:SeparatorChar = &apos; &apos;">
														<xsl:for-each select="n1:SeparatorChar">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
												<xsl:for-each select="n1:SeparatorChar">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
												<xsl:for-each select="n1:SeparatorChar">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
											<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
												<xsl:for-each select="n1:SeparatorChar">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:when>
										</xsl:choose>
									</td>
								</tr>
							</tbody>
						</table>
						<span>
							<xsl:text>&#160;</xsl:text>
						</span>
						<table style="width:25cm; " border="0" cellpadding="3" cellspacing="0">
							<xsl:variable name="altova:CurrContextGrid_06B5B318" select="."/>
							<thead style="background-color:#d9f5ff; ">
								<tr>
									<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; text-align:center; width:4cm; ">
										<span>
											<xsl:text>Term Name</xsl:text>
										</span>
									</th>
									<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; text-align:center; width:4cm; ">
										<span>
											<xsl:text>Plural</xsl:text>
										</span>
									</th>
									<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; text-align:center; width:4cm; ">
										<span>
											<xsl:text>Abbreviation</xsl:text>
										</span>
									</th>
									<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; text-align:center; width:4cm; ">
										<span>
											<xsl:text>Alt Abbreviation</xsl:text>
										</span>
									</th>
									<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; text-align:center; width:1cm; ">
										<span>
											<xsl:text>P</xsl:text>
										</span>
									</th>
									<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; text-align:center; width:1cm; ">
										<span>
											<xsl:text>C</xsl:text>
										</span>
									</th>
									<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; text-align:center; width:1cm; ">
										<span>
											<xsl:text>M</xsl:text>
										</span>
									</th>
									<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; text-align:center; width:1cm; ">
										<span>
											<xsl:text>Q</xsl:text>
										</span>
									</th>
									<th style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; border-top-color:black; border-top-style:solid; border-top-width:thin; font-size:xx-small; font-weight:bold; text-align:center; width:5cm; ">
										<span>
											<xsl:text>Short Description</xsl:text>
										</span>
									</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="n1:GlossaryCollection">
									<xsl:for-each select="n1:GlossaryDetail">
										<tr>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-left-color:black; border-left-style:solid; border-left-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:left; vertical-align:top; width:4cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:TermName">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:TermName) &gt; 0">
																<xsl:for-each select="n1:TermName">
																	<span style="font-size:xx-small; ">
																		<xsl:apply-templates/>
																	</span>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:TermName">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:TermName">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:TermName">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; width:4cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:Plural">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:Plural) &gt; 0">
																<xsl:for-each select="n1:Plural">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:Plural">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:Plural">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:Plural">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:4cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:Abbreviation">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:Abbreviation) &gt; 0">
																<xsl:for-each select="n1:Abbreviation">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:Abbreviation">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:Abbreviation">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:Abbreviation">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; width:4cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:AltAbbreviation">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:AltAbbreviation) &gt; 0">
																<xsl:for-each select="n1:AltAbbreviation">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:AltAbbreviation">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:AltAbbreviation">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:AltAbbreviation">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:1cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:P">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:P) &gt; 0">
																<xsl:for-each select="n1:P">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:P">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:P">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:P">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:1cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:C">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:C) &gt; 0">
																<xsl:for-each select="n1:C">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:C">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:C">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:C">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; width:1cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:M">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:M) &gt; 0">
																<xsl:for-each select="n1:M">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:M">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:M">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:M">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; text-align:center; vertical-align:top; width:1cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:Q">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="string-length(n1:q) &gt; 0">
																<xsl:for-each select="n1:Q">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:for-each select="n1:Q">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:Q">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:Q">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
											<td style="border-bottom-color:black; border-bottom-style:solid; border-bottom-width:thin; border-right-color:black; border-right-style:solid; border-right-width:thin; font-size:xx-small; vertical-align:top; width:5cm; ">
												<xsl:choose>
													<xsl:when test="$SV_OutputFormat = &apos;Authentic&apos;">
														<xsl:for-each select="n1:SDescription">
															<xsl:for-each select="n1:SDescriptionDetails">
																<xsl:for-each select="n1:SDescriptionRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;HTML&apos;">
														<xsl:choose>
															<xsl:when test="count(n1:SDescription/n1:SDescriptionDetails/n1:SDescriptionRow) &gt; 0">
																<xsl:for-each select="n1:SDescription">
																	<xsl:for-each select="n1:SDescriptionDetails">
																		<xsl:for-each select="n1:SDescriptionRow">
																			<xsl:apply-templates/>
																			<br/>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise>
																<span>
																	<xsl:text>&#160;</xsl:text>
																</span>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;RTF&apos;">
														<xsl:choose>
															<xsl:when test="count(n1:SDescription/n1:SDescriptionDetails/n1:SDescriptionRow) &gt; 0">
																<xsl:for-each select="n1:SDescription">
																	<xsl:for-each select="n1:SDescriptionDetails">
																		<xsl:for-each select="n1:SDescriptionRow">
																			<xsl:apply-templates/>
																			<br/>
																		</xsl:for-each>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:when>
															<xsl:otherwise/>
														</xsl:choose>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;PDF&apos;">
														<xsl:for-each select="n1:SDescription">
															<xsl:for-each select="n1:SDescriptionDetails">
																<xsl:for-each select="n1:SDescriptionRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
													<xsl:when test="$SV_OutputFormat = &apos;Word2007&apos;">
														<xsl:for-each select="n1:SDescription">
															<xsl:for-each select="n1:SDescriptionDetails">
																<xsl:for-each select="n1:SDescriptionRow">
																	<xsl:apply-templates/>
																	<br/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:when>
												</xsl:choose>
											</td>
										</tr>
									</xsl:for-each>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
