-- Permissions needed by oracle user to use reporting schema functionality
CREATE OR REPLACE DIRECTORY OSDDM_REPORTS_DIR AS <OS DIRECTORY>;
GRANT READ, WRITE ON DIRECTORY OSDDM_REPORTS_DIR TO <USER>;
GRANT CREATE SESSION TO <USER>;
GRANT RESOURCE TO <USER>;
GRANT CREATE TABLE TO <USER>;
GRANT CREATE SEQUENCE TO <USER>;
GRANT CREATE VIEW TO <USER>;
GRANT CREATE PROCEDURE TO <USER>;

-- Oracle Database 10g Express Edition only
GRANT EXECUTE ON UTL_FILE TO public;
